stages:
  - build
  - deploy

variables:
  IMAGE_NAME: haitn2806/ucam-ui
  IMAGE_TAG: v0

before_script:
  - docker info

build:
  stage: build
  image: docker:20.10.16
  before_script:
    - cd ui
    - docker login -u $USER_NAME_HUB -p $PASSWORD_HUB
  script:
    - echo "Building the project..."
    - docker build -t $IMAGE_NAME .
# deploy:
#   stage: deploy
#   script:
#     - echo "Deploying the project..."
#     - docker run -d $IMAGE_NAME
#   only:
#     - master
