export const RIGHT_ANSWERS = [
    'Ô mai chuối! Bạn làm chuẩn vậy.',
    'Đúng roài!',
    'Bạn trả lời ở tầm vũ trụ luôn rồi',
    'Ghê chưa. Cao thủ ở đây chứ đâu!',
    'Nếu cuộc đời là những ngã rẽ thì bạn tôi toàn rẽ đúng hướng không ah',
    'Tôi đố bạn trả lời đúng tiếp câu sau đấy!',
    'Ối zồi ôi, đỉnh của chóp là đây chứ đâu!',
    'Nhà tiên tri vũ trụ lại trả lời đúng rồi!',
    'Bạn làm đúng tiếp câu sau thì mai bạn sẽ có người yêu!',
    'Bạn hay trúng số lắm đúng không! Sao làm đúng hoài zậy!',
    'Cũng được!',
    'Bạn thì kinh rồi!',
    'Bái phục! 10đ về chỗ!',
]

export const WRONG_ANSWERS = [
    'Rất tiếc, bạn đã lỡ chạm tay vào phương án sai. Bạn hãy suy nghĩ kỹ để trả lời lại nhé!',
    'Teeeeee è, âm thanh phát ra mùi sai sai. Bạn làm lại bài này nhé!',
    'Bạn sai rồi, bạn đã sai thật rồi…chần chờ gì nữa mà không khoanh ngay vào phương án đúng bạn eii!',
    'Sai!',
    'Chưa chính xác!',
    'Tỉnh ngay đi bạn ơi, không là không ai cứu bạn được đâu. Chọn lại nào!',
    'Sai rồi, theo tôi bạn nên đi làm gói café rồi quay lại làm tiếp!',
    'Chưa đúng, tôi đố bạn làm lại mà đúng luôn câu này đấy!',
    'Bất ngờ chưa bà zà',
    'Toang, toang thật rồi. Hãy đứng dậy rửa mặt cho tỉnh táo rồi vào gặp tôi để làm tiếp nào!',
    'Bạn ăn gì tôi cúng, sai hoài ah!',
    'Đúng là dân ế lâu năm có khác. Cừ đè phương án sai để chọn là sao!',
    'Hải! Quay xe!',
]
